using System.Reflection;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyCompany("Matt Hamilton")]
[assembly: AssemblyProduct("PSycheTest")]
[assembly: AssemblyCopyright("© 2013 Matt Hamilton All Rights Reserved.")]


// The Product version of the assembly. This is the version common across all files included
// with the product, and is the customer-facing version. Whilst this version can be a string, 
// (such as '1.0 Release Candidate'), the value here is expected to be in format 
// Major.Minor.Revision. The Build Number is generated by the (Production) build process.
//
// Example syntax: "1.0.0"
[assembly: AssemblyInformationalVersion("1.0")]

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif